# Generated by Django 5.2.3 on 2025-09-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_review_rating_between_1_and_5_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='rating_between_1_and_5',
        ),
    ]
